//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forum.FørOpg2.Models1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrugerTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BrugerTB()
        {
            this.BeskedTB = new HashSet<BeskedTB>();
        }
    
        public int Bruger_ID { get; set; }
        public string Username { get; set; }
        public string Parsword { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BeskedTB> BeskedTB { get; set; }
    }
}
