//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forum.FørOpg2
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeskedTB
    {
        public int Besked_ID { get; set; }
        public int Bruger_ID { get; set; }
        public int Forum_ID { get; set; }
        public string Besked_content { get; set; }
    
        public virtual BrugerTB BrugerTB { get; set; }
        public virtual ForumTB ForumTB { get; set; }
    }
}
