//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forum.FørOpg2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChatDatabaseEntities : DbContext
    {
        public ChatDatabaseEntities()
            : base("name=ChatDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BeskedTB> BeskedTBs { get; set; }
        public virtual DbSet<BrugerTB> BrugerTBs { get; set; }
        public virtual DbSet<ForumTB> ForumTBs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
